export const REQUESTING_AUTOCOMPLETE = 'REQUESTING_AUTOCOMPLETE';
export const DONE_REQUEST_AUTOCOMPLETE = 'DONE_REQUEST_AUTOCOMPLETE';
export const FAILED_REQUEST_AUTOCOMPLETE = 'FAILED_REQUEST_AUTOCOMPLETE';